CREATE TABLE IF NOT EXISTS PRODUTO (
    produto_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    data_inclusao TIMESTAMP(6) NOT NULL,
    descricao CHARACTER VARYING(255) NOT NULL,
    nome CHARACTER VARYING(255) NOT NULL,
    valor NUMERIC(38, 2) NOT NULL,
    situacao SMALLINT
);

CREATE TABLE IF NOT EXISTS CATEGORIA (
    categoria_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome CHARACTER VARYING(255) NOT NULL
);
